#!/usr/bin/env bash

make tlf

bash bash/rbwgyo.bash >/tmp/im1.txt
c/top-left-front </tmp/im1.txt >/tmp/im2.txt
cat /tmp/im2.txt | tr -d ' \n' | xargs php7.2 php/imagecube.php

rm /tmp/im1.txt /tmp/im2.txt
